"use client";

import type { LucideIcon } from "lucide-react";
import {
  Ban,
  Bell,
  Calendar,
  CheckCircle2,
  Clock,
  Cog,
  Eye,
  Wrench,
  Zap,
} from "lucide-react";
import { useState } from "react";

import { useUser } from "@/context/user-context";
import {
  useGetMaintenanceQuery,
  useSubmitPreUseCheckMutation,
  useUpdatePmRuleMutation,
  useUpdateWorkOrderStatusMutation,
} from "@/hooks/api/fixed-assets";

import {
  CatCell,
  flexCol,
  flexRow,
  iconBox,
  mono,
  muted,
  TD,
  TH,
} from "./FaMaintenanceTabs";
import { FaQueryState } from "./FaQueryState";

const WO_FILTERS = ["All", "Open", "In-progress", "Critical", "Predictive"];
const SOURCE_MAP: Record<string, { icon: LucideIcon; label: string }> = {
  corrective: { icon: Wrench, label: "Corrective" },
  inspection: { icon: Eye, label: "Inspection" },
  pm: { icon: Calendar, label: "PM" },
  predictive: { icon: Zap, label: "Predictive" },
};

const priorityBadge = (p: string): string =>
  p === "critical" ? "danger" : p === "high" ? "warn" : "outline";

export function WoTab() {
  const { tokenPayload } = useUser();
  const organizationId = tokenPayload?.organization_id ?? "";
  const { data: resp, isError, isLoading } = useGetMaintenanceQuery({ organizationId });
  const { mutateAsync: updateWoStatus } = useUpdateWorkOrderStatusMutation({
    organizationId,
  });
  const WORK_ORDERS = resp?.data?.work_orders ?? [];
  const [filter, setFilter] = useState("All");
  const [selectedId, setSelectedId] = useState("");
  const queue = WORK_ORDERS.filter((w) => {
    if (filter === "All") return true;
    if (filter === "Open") return w.status === "open";
    if (filter === "In-progress") return w.status === "in-progress";
    if (filter === "Critical") return w.priority === "critical";
    if (filter === "Predictive") return w.type === "predictive";
    return true;
  });
  const wo = WORK_ORDERS.find((w) => w.id === selectedId) ?? WORK_ORDERS[0];  const src = SOURCE_MAP[wo.type] ?? SOURCE_MAP.corrective;
  const SrcIcon = src.icon;
  const srcDesc =
    wo.type === "predictive"
      ? "Triggered by AI anomaly detection on sensor baseline"
      : wo.type === "pm"
        ? "Generated by scheduled PM rule"
        : "Manually created from inspection or request";
  return (
    <FaQueryState
      emptyDescription="No work orders in the queue."
      emptyTitle="No work orders"
      isEmpty={WORK_ORDERS.length === 0}
      isError={isError}
      isLoading={isLoading}
    >
      <div className="ks-grid-2">
        <div className="ks-card">
          <div className="ks-card-head">
            <div className="ks-card-title">Work order queue</div>
            <div className="ks-chips">
              {WO_FILTERS.map((f) => (
                <button
                  key={f}
                  className={`ks-chip ${filter === f ? "on" : ""}`}
                  type="button"
                  onClick={() => setFilter(f)}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
          <table className="w-full text-sm">
            <thead>
              <tr>
                {["WO", "Asset", "Source", "Priority", "Status"].map((c) => (
                  <TH key={c}>{c}</TH>
                ))}
              </tr>
            </thead>
            <tbody>
              {queue.map((w) => (
                <tr
                  key={w.id}
                  style={{ background: w.id === selectedId ? "hsl(var(--surface-2))" : "transparent", cursor: "pointer" }}
                  onClick={() => setSelectedId(w.id)}
                >
                  <TD>
                    <span style={{ ...mono, fontSize: 12, fontWeight: 600 }}>{w.id}</span>
                  </TD>
                  <TD>
                    <div style={{ fontSize: 12, fontWeight: 600 }}>{w.asset}</div>
                    <div style={{ ...muted, fontSize: 11 }}>{w.asset_id}</div>
                  </TD>
                  <TD>
                    <span className="ks-badge outline">
                      <SrcIcon size={10} />
                      {src.label}
                    </span>
                  </TD>
                  <TD>
                    <span className={`ks-badge ${priorityBadge(w.priority)}`}>{w.priority}</span>
                  </TD>
                  <TD>
                    <span className={`ks-badge ${w.status === "in-progress" ? "info" : "outline"}`}>
                      {w.status}
                    </span>
                  </TD>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="ks-card">
          <div className="ks-card-head">
            <div>
              <div className="ks-card-title">{wo.id}</div>
              <div className="ks-card-desc">{wo.asset}</div>
            </div>
            <span className={`ks-badge ${priorityBadge(wo.priority)}`}>{wo.priority}</span>
          </div>
          <div className="ks-card-body" style={{ ...flexCol, gap: 14 }}>
            <div
              style={{
                alignItems: "flex-start",
                background: "hsl(var(--surface-2))",
                borderRadius: 8,
                display: "flex",
                gap: 10,
                padding: 12,
              }}
            >
              <SrcIcon size={15} style={{ color: "hsl(var(--brand))", flexShrink: 0, marginTop: 2 }} />
              <div>
                <div style={{ fontSize: 12, fontWeight: 600 }}>Source · {src.label}</div>
                <div style={{ ...muted, marginTop: 2 }}>{srcDesc}</div>
              </div>
            </div>

            <div>
              <div style={{ ...muted, marginBottom: 4 }}>Issue</div>
              <div style={{ fontSize: 13 }}>{wo.desc}</div>
            </div>

            <div style={{ display: "flex", flexWrap: "wrap", gap: 16 }}>
              {[
                ["Assigned", wo.assigned_to],
                ["ETA", wo.eta],
                ["Created", wo.created_at],
              ].map(([k, v]) => (
                <div key={k}>
                  <div style={{ ...muted, fontSize: 11 }}>{k}</div>
                  <div style={{ fontSize: 13, fontWeight: 600 }}>{v}</div>
                </div>
              ))}
            </div>

            <div>
              <div style={{ ...muted, marginBottom: 6 }}>Connected events</div>
              <div style={{ ...flexCol, gap: 6 }}>
                <div style={{ ...flexRow, fontSize: 12, gap: 8 }}>
                  <Bell size={12} style={{ color: "hsl(var(--text-3))" }} />
                  RFID scan anomaly · 2h ago
                </div>
                <div style={{ ...flexRow, fontSize: 12, gap: 8 }}>
                  <Clock size={12} style={{ color: "hsl(var(--text-3))" }} />
                  Pre-use check flagged · {wo.created_at}
                </div>
              </div>
            </div>

            <div style={{ display: "flex", gap: 8 }}>
              <button
                className="ks-btn ks-btn-primary"
                type="button"
                onClick={() =>
                  updateWoStatus({
                    data: { status: "in-progress" },
                    workOrderId: wo.id,
                  })
                }
              >
                Start work
              </button>
              <button
                className="ks-btn"
                type="button"
                onClick={() =>
                  updateWoStatus({
                    data: { status: "done" },
                    workOrderId: wo.id,
                  })
                }
              >
                <CheckCircle2 size={13} />
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
    </FaQueryState>
  );
}

export function ScheduleTab() {
  const { tokenPayload } = useUser();
  const organizationId = tokenPayload?.organization_id ?? "";
  const { data: resp, isError, isLoading } = useGetMaintenanceQuery({ organizationId });
  const { mutateAsync: submitCheck } = useSubmitPreUseCheckMutation({
    organizationId,
  });
  const { mutateAsync: updatePmRule } = useUpdatePmRuleMutation({
    organizationId,
  });
  const PRE_USE_ASSETS = resp?.data?.pre_use_assets ?? [];
  const PM_SCHEDULE = resp?.data?.pmSchedule ?? [];
  const PM_RULES = resp?.data?.pm_rules ?? [];
  const [view, setView] = useState<"preuse" | "pm">("preuse");
  const [selAsset, setSelAsset] = useState("");
  const asset = PRE_USE_ASSETS.find((a) => a.id === selAsset) ?? PRE_USE_ASSETS[0];
  return (
    <div>
      <div className="ks-seg" style={{ marginBottom: 16 }}>
        <button
          className={view === "preuse" ? "on" : ""}
          type="button"
          onClick={() => setView("preuse")}
        >
          Pre-Use Inspection
        </button>
        <button
          className={view === "pm" ? "on" : ""}
          type="button"
          onClick={() => setView("pm")}
        >
          Scheduled PM
        </button>
      </div>

      <FaQueryState
        emptyDescription={view === "preuse" ? "No assets require pre-use inspection." : "No PM schedule entries."}
        emptyTitle={view === "preuse" ? "No inspections due" : "No PM scheduled"}
        isEmpty={view === "preuse" ? PRE_USE_ASSETS.length === 0 : PM_SCHEDULE.length === 0 && PM_RULES.length === 0}
        isError={isError}
        isLoading={isLoading}
      >
        {view === "preuse" ? (
        <div className="ks-grid-2">
          <div className="ks-card">
            <div className="ks-card-head">
              <div className="ks-card-title">Inspection required</div>
              <span className="ks-badge warn">
                {PRE_USE_ASSETS.filter((a) => a.overdue).length} overdue
              </span>
            </div>
            <table className="w-full text-sm">
              <thead>
                <tr>
                  {["Asset", "Due", "Streak", "Result"].map((c) => (
                    <TH key={c}>{c}</TH>
                  ))}
                </tr>
              </thead>
              <tbody>
                {PRE_USE_ASSETS.map((a) => (
                  <tr
                    key={a.id}
                    style={{
                      background: a.id === selAsset ? "hsl(var(--surface-2))" : "transparent",
                      cursor: "pointer",
                    }}
                    onClick={() => setSelAsset(a.id)}
                  >
                    <TD>
                      <CatCell cat={a.cat} name={a.asset} />
                      <div style={{ ...muted, fontSize: 11, marginTop: 2 }}>{a.id}</div>
                    </TD>
                    <TD>
                      <span
                        style={{
                          ...mono,
                          color: a.overdue ? "hsl(var(--destructive))" : "inherit",
                          fontSize: 12,
                          fontWeight: a.overdue ? 600 : 400,
                        }}
                      >
                        {a.dueIn}
                      </span>
                    </TD>
                    <TD style={mono}>{a.streak}x</TD>
                    <TD>
                      <span className={`ks-badge ${a.last_result === "pass" ? "success" : "danger"}`}>
                        {a.last_result === "pass" ? <CheckCircle2 size={11} /> : <Ban size={11} />}
                        {a.last_result}
                      </span>
                    </TD>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="ks-card">
            <div className="ks-card-head">
              <div>
                <div className="ks-card-title">{asset.asset}</div>
                <div className="ks-card-desc">
                  {asset.interval} · last by {asset.last_checker} ({asset.lastCheckLabel})
                </div>
              </div>
              {asset.critical && <span className="ks-badge danger">Critical</span>}
            </div>
            <div className="ks-card-body">
              {asset.fail_item && (
                <div
                  style={{
                    alignItems: "center",
                    background: "hsl(var(--danger-soft))",
                    borderRadius: 8,
                    color: "hsl(var(--destructive))",
                    display: "flex",
                    fontSize: 12,
                    gap: 8,
                    marginBottom: 12,
                    padding: 10,
                  }}
                >
                  <Ban size={14} />
                  {asset.fail_item}
                </div>
              )}
              <div style={{ ...muted, marginBottom: 8 }}>
                Checklist ({asset.checks.length} items)
              </div>
              <div style={{ ...flexCol, gap: 8 }}>
                {asset.checks.map((c) => (
                  <div key={c} style={{ ...flexRow, fontSize: 13, gap: 10 }}>
                    <CheckCircle2 size={15} style={{ color: "hsl(var(--success))" }} />
                    {c}
                  </div>
                ))}
              </div>
              <button
                className="ks-btn ks-btn-primary"
                style={{ marginTop: 14, width: "100%" }}
                type="button"
                onClick={() =>
                  submitCheck({
                    asset_id: asset.id,
                    checker: asset.last_checker,
                    fail_item: asset.fail_item,
                    overall_result: asset.fail_item ? "fail" : "pass",
                    results: asset.checks.map((check) => ({
                      check,
                      passed: !asset.fail_item,
                    })),
                  })
                }
              >
                Submit inspection
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="ks-grid-2">
          <div className="ks-card">
            <div className="ks-card-head">
              <div className="ks-card-title">PM schedule</div>
              <span className="ks-badge outline">{PM_SCHEDULE.length} upcoming</span>
            </div>
            <div className="ks-card-body" style={{ ...flexCol, gap: 10 }}>
              {PM_SCHEDULE.map((p) => (
                <div
                  key={p.id}
                  style={{ border: "1px solid hsl(var(--border))", borderRadius: 8, display: "flex", gap: 10, padding: 10 }}
                >
                  <div style={iconBox(32)}>
                    <Cog size={14} />
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 13, fontWeight: 600 }}>{p.task}</div>
                    <div style={{ ...muted, marginTop: 2 }}>
                      {p.asset} · {p.who}
                    </div>
                    <div style={{ ...flexRow, ...muted, fontSize: 11, gap: 10, marginTop: 4 }}>
                      <span>{p.when}</span>
                      <span>· {p.date}</span>
                      <span>· ETA {p.eta}</span>
                    </div>
                  </div>
                  <span className={`ks-badge ${p.tone || "outline"}`}>{p.type}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="ks-card">
            <div className="ks-card-head">
              <div className="ks-card-title">PM rules</div>
              <span className="ks-badge brand">Auto-WO on</span>
            </div>
            <div className="ks-card-body" style={{ ...flexCol, gap: 10 }}>
              {PM_RULES.map((r) => (
                <div
                  key={r.name}
                  style={{ border: "1px solid hsl(var(--border))", borderRadius: 8, padding: 10 }}
                >
                  <div style={{ ...flexRow, gap: 6 }}>
                    <span style={{ fontSize: 13, fontWeight: 600 }}>{r.name}</span>
                    <span className={`ks-badge ${r.tone || "outline"}`} style={{ marginLeft: "auto" }}>
                      {r.scope}
                    </span>
                    <button
                      className={`ks-btn ks-btn-sm ${r.auto_wo ? "ks-btn-primary" : ""}`}
                      type="button"
                      onClick={() =>
                        updatePmRule({
                          data: { auto_wo: !r.auto_wo },
                          pmRuleId: r.name,
                        })
                      }
                    >
                      <Zap size={12} />
                      {r.auto_wo ? "Auto-WO" : "Manual"}
                    </button>
                  </div>
                  <div style={{ ...flexRow, ...muted, gap: 12, marginTop: 6 }}>
                    <span>Trigger: {r.trigger}</span>
                    <span>· Remind: {r.remind}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
      </FaQueryState>
    </div>
  );
}
